version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - API_KEY=${API_KEY}
      - UNSPLASH_ACCESS_KEY=${UNSPLASH_ACCESS_KEY}
      # - ALLOWED_ORIGIN=http://localhost:3000
    env_file:
      - .env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    env_file:
      - .env